// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sgcf.Infrastructure.Persistence;

#nullable disable

namespace Sgcf.Infrastructure.Migrations
{
    [DbContext(typeof(SgcfDbContext))]
    [Migration("20260511170000_Fase6HedgeMtm")]
    partial class Fase6HedgeMtm
    {
    }
}
