// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sgcf.Infrastructure.Persistence;

#nullable disable

namespace Sgcf.Infrastructure.Migrations
{
    [DbContext(typeof(SgcfDbContext))]
    [Migration("20260511115826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sgcf")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sgcf.Domain.Bancos.Banco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AceitaLiquidacaoParcial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aceita_liquidacao_parcial");

                    b.Property<bool>("AceitaLiquidacaoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aceita_liquidacao_total");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apelido");

                    b.Property<short>("AvisoPrevioMinDiasUteis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("aviso_previo_min_dias_uteis");

                    b.Property<decimal?>("BreakFundingFeePctDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("break_funding_fee_pct");

                    b.Property<string>("CodigoCompe")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo_compe");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExigeAnuenciaExpressa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exige_anuencia_expressa");

                    b.Property<bool>("ExigeParcelaInteira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exige_parcela_inteira");

                    b.Property<string>("ObservacoesAntecipacao")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_antecipacao");

                    b.Property<short>("PadraoAntecipacao")
                        .HasColumnType("smallint")
                        .HasColumnName("padrao_antecipacao");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<decimal?>("TlaPctPorMesRemanescenteDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tla_pct_por_mes_remanescente");

                    b.Property<decimal?>("TlaPctSobreSaldoDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tla_pct_sobre_saldo");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorMinimoParcialPctDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("valor_minimo_parcial_pct");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCompe")
                        .IsUnique();

                    b.ToTable("banco_config", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BancoId")
                        .HasColumnType("uuid")
                        .HasColumnName("banco_id");

                    b.Property<short>("BaseCalculo")
                        .HasColumnType("smallint")
                        .HasColumnName("base_calculo");

                    b.Property<Guid?>("ContratoPaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_pai_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<LocalDate>("DataContratacao")
                        .HasColumnType("date")
                        .HasColumnName("data_contratacao");

                    b.Property<LocalDate>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda");

                    b.Property<string>("NumeroExterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_externo");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaAaDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("taxa_aa");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorPrincipalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_principal");

                    b.HasKey("Id");

                    b.HasIndex("BancoId")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("ContratoPaiId")
                        .HasFilter("contrato_pai_id IS NOT NULL");

                    b.HasIndex("DataVencimento")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Status")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("contrato", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Garantia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<LocalDate?>("DataVigenciaFim")
                        .HasColumnType("date")
                        .HasColumnName("data_vigencia_fim");

                    b.Property<LocalDate>("DataVigenciaIni")
                        .HasColumnType("date")
                        .HasColumnName("data_vigencia_ini");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "Tipo", "DataVigenciaIni")
                        .IsUnique();

                    b.ToTable("garantia", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<LocalDate?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<LocalDate>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorJurosDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_juros");

                    b.Property<decimal?>("ValorPagoDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_pago");

                    b.Property<decimal>("ValorPrincipalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_principal");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("ContratoId", "Numero")
                        .IsUnique();

                    b.ToTable("parcela", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Cotacoes.CotacaoFx", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fonte");

                    b.Property<string>("MoedaBase")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_base");

                    b.Property<string>("MoedaQuote")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_quote");

                    b.Property<Instant>("Momento")
                        .HasColumnType("timestamptz")
                        .HasColumnName("momento");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorCompraDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_compra");

                    b.Property<decimal>("ValorVendaDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_venda");

                    b.HasKey("Id");

                    b.HasIndex("MoedaBase", "Tipo", "Momento");

                    b.HasIndex("MoedaBase", "MoedaQuote", "Momento", "Tipo")
                        .IsUnique();

                    b.ToTable("cotacao_fx", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Hedge.InstrumentoHedge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContraparteId")
                        .HasColumnType("uuid")
                        .HasColumnName("contraparte_id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<LocalDate>("DataContratacao")
                        .HasColumnType("date")
                        .HasColumnName("data_contratacao");

                    b.Property<LocalDate>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("MoedaBase")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_base");

                    b.Property<string>("MoedaQuote")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_quote");

                    b.Property<decimal>("NotionalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("notional");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("StrikeCall")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("strike_call");

                    b.Property<decimal?>("StrikeForward")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("strike_forward");

                    b.Property<decimal?>("StrikePut")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("strike_put");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("instrumento_hedge", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Garantia", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Contrato", null)
                        .WithMany("Garantias")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Parcela", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Contrato", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Contrato", b =>
                {
                    b.Navigation("Garantias");

                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
