// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sgcf.Infrastructure.Persistence;

#nullable disable

namespace Sgcf.Infrastructure.Migrations
{
    [DbContext(typeof(SgcfDbContext))]
    [Migration("20260514162955_CalendarioFeriado")]
    partial class CalendarioFeriado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sgcf")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sgcf.Domain.Alertas.AlertaExposicaoBanco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BancoId")
                        .HasColumnType("uuid")
                        .HasColumnName("banco_id");

                    b.Property<Instant>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<LocalDate>("DataAlerta")
                        .HasColumnType("date")
                        .HasColumnName("data_alerta");

                    b.Property<decimal>("ExposicaoBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("exposicao_brl");

                    b.Property<decimal>("LimiteBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("limite_brl");

                    b.Property<decimal>("PercentualOcupacao")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_ocupacao");

                    b.HasKey("Id");

                    b.HasIndex("BancoId", "DataAlerta")
                        .IsUnique()
                        .HasDatabaseName("UX_alerta_exposicao_banco_banco_data");

                    b.ToTable("alerta_exposicao_banco", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Alertas.AlertaVencimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<LocalDate>("DataAlerta")
                        .HasColumnType("date")
                        .HasColumnName("data_alerta");

                    b.Property<LocalDate>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_alerta");

                    b.Property<decimal>("ValorDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "TipoAlerta", "DataVencimento")
                        .IsUnique()
                        .HasDatabaseName("UX_alerta_vencimento_contrato_tipo_data");

                    b.ToTable("alerta_vencimento", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Antecipacao.SimulacaoAntecipacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComponentesCustoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("componentes_custo");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<decimal?>("CotacaoAplicada")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cotacao_aplicada");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<LocalDate>("DataEfetivaProposta")
                        .HasColumnType("date")
                        .HasColumnName("data_efetiva_proposta");

                    b.Property<Instant>("DataSimulacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_simulacao");

                    b.Property<decimal?>("EconomiaEstimadaBrlValor")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("economia_estimada_brl");

                    b.Property<string>("ObservacoesBanco")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_banco");

                    b.Property<short>("PadraoAplicado")
                        .HasColumnType("smallint")
                        .HasColumnName("padrao_aplicado");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TaxaMercadoAtualAa")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("taxa_mercado_atual_aa");

                    b.Property<short>("TipoAntecipacao")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_antecipacao");

                    b.Property<short>("ValorPrincipalAQuitarMoedaId")
                        .HasColumnType("smallint")
                        .HasColumnName("valor_principal_a_quitar_moeda");

                    b.Property<decimal>("ValorPrincipalAQuitarValor")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_principal_a_quitar");

                    b.Property<decimal>("ValorTotalSimuladoBrlValor")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_total_simulado_brl");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "DataSimulacao")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_simulacao_contrato");

                    b.ToTable("simulacao_antecipacao", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Bancos.Banco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AceitaLiquidacaoParcial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aceita_liquidacao_parcial");

                    b.Property<bool>("AceitaLiquidacaoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aceita_liquidacao_total");

                    b.Property<bool>("AceitaRefinimp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aceita_refinimp");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apelido");

                    b.Property<short>("AvisoPrevioMinDiasUteis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("aviso_previo_min_dias_uteis");

                    b.Property<decimal?>("BreakFundingFeePctDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("break_funding_fee_pct");

                    b.Property<string>("CodigoCompe")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo_compe");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExigeAnuenciaExpressa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exige_anuencia_expressa");

                    b.Property<bool>("ExigeParcelaInteira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("exige_parcela_inteira");

                    b.Property<decimal?>("LimiteCreditoBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("limite_credito_brl");

                    b.Property<string>("ObservacoesAntecipacao")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_antecipacao");

                    b.Property<short>("PadraoAntecipacao")
                        .HasColumnType("smallint")
                        .HasColumnName("padrao_antecipacao");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<decimal?>("TlaPctPorMesRemanescenteDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tla_pct_por_mes_remanescente");

                    b.Property<decimal?>("TlaPctSobreSaldoDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tla_pct_sobre_saldo");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ValorMinimoParcialPctDecimal")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("valor_minimo_parcial_pct");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCompe")
                        .IsUnique();

                    b.ToTable("banco_config", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Calendario.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AnoReferencia")
                        .HasColumnType("smallint")
                        .HasColumnName("ano_referencia");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<LocalDate>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("descricao");

                    b.Property<byte>("Escopo")
                        .HasColumnType("smallint")
                        .HasColumnName("escopo");

                    b.Property<byte>("Fonte")
                        .HasColumnType("smallint")
                        .HasColumnName("fonte");

                    b.Property<byte>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AnoReferencia", "Escopo");

                    b.HasIndex("Data", "Tipo", "Escopo")
                        .IsUnique();

                    b.ToTable("feriado", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contabilidade.LancamentoContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<LocalDate>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("MoedaContrato")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_contrato");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("origem");

                    b.Property<decimal>("ValorDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "Data", "Origem")
                        .IsUnique()
                        .HasDatabaseName("UX_lancamento_contabil_contrato_data_origem");

                    b.ToTable("lancamento_contabil", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contabilidade.PlanoContasGerencial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("CodigoGerencial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text")
                        .HasColumnName("codigo_gerencial");

                    b.Property<string>("CodigoSapB1")
                        .HasColumnType("text")
                        .HasColumnName("codigo_sap_b1");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("natureza");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CodigoGerencial")
                        .IsUnique();

                    b.ToTable("plano_contas_gerencial", "sgcf");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Ativo = true,
                            CodigoGerencial = "1.1.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "ATIVO",
                            Nome = "Conta Corrente em BRL",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Ativo = true,
                            CodigoGerencial = "1.1.2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "ATIVO",
                            Nome = "CDBs e Aplicações Livres",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Ativo = true,
                            CodigoGerencial = "1.2.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "ATIVO",
                            Nome = "CDB Cativo (Cash Collateral)",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Ativo = true,
                            CodigoGerencial = "1.2.2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "ATIVO",
                            Nome = "Outras Garantias Bloqueadas",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Ativo = true,
                            CodigoGerencial = "1.3.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "ATIVO",
                            Nome = "NDFs a Receber",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Ativo = true,
                            CodigoGerencial = "2.1.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "FINIMP em Moeda Estrangeira",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Ativo = true,
                            CodigoGerencial = "2.1.2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "4131 em Moeda Estrangeira",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Ativo = true,
                            CodigoGerencial = "2.1.3",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "NCE/CCE em BRL",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Ativo = true,
                            CodigoGerencial = "2.1.4",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "Balcão Caixa",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Ativo = true,
                            CodigoGerencial = "2.1.5",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "FGI (BNDES via Banco Intermediário)",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Ativo = true,
                            CodigoGerencial = "2.1.6",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "REFINIMPs Ativos",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Ativo = true,
                            CodigoGerencial = "2.2.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "NDFs a Pagar",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Ativo = true,
                            CodigoGerencial = "2.3.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "Juros Provisionados FINIMP",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Ativo = true,
                            CodigoGerencial = "2.3.2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "Juros Provisionados 4131",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            Ativo = true,
                            CodigoGerencial = "2.3.3",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "Juros Provisionados Outros",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000011"),
                            Ativo = true,
                            CodigoGerencial = "2.4.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "IRRF s/ Juros Remetidos ao Exterior",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000012"),
                            Ativo = true,
                            CodigoGerencial = "2.4.2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "PASSIVO",
                            Nome = "IOF Câmbio a Recolher",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Ativo = true,
                            CodigoGerencial = "3.1.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Rendimento de CDB Cativo",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Ativo = true,
                            CodigoGerencial = "3.1.2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Ganho com NDF (MTM e Liquidação)",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Ativo = true,
                            CodigoGerencial = "3.1.3",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Variação Cambial Ativa",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Ativo = true,
                            CodigoGerencial = "3.2.1",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Juros sobre FINIMP",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Ativo = true,
                            CodigoGerencial = "3.2.2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Juros sobre 4131",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Ativo = true,
                            CodigoGerencial = "3.2.3",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Juros sobre Demais Modalidades",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Ativo = true,
                            CodigoGerencial = "3.2.4",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "IRRF Gross-Up",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            Ativo = true,
                            CodigoGerencial = "3.2.5",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "IOF Câmbio",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000009"),
                            Ativo = true,
                            CodigoGerencial = "3.2.6",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Comissões SBLC, CPG e Garantia",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000010"),
                            Ativo = true,
                            CodigoGerencial = "3.2.7",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Tarifas (ROF, CADEMP, Cartório)",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000011"),
                            Ativo = true,
                            CodigoGerencial = "3.2.8",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Perda com NDF (MTM e Liquidação)",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000012"),
                            Ativo = true,
                            CodigoGerencial = "3.2.9",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Variação Cambial Passiva",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000013"),
                            Ativo = true,
                            CodigoGerencial = "3.2.10",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L),
                            Natureza = "RESULTADO",
                            Nome = "Custo de Oportunidade do CDB Cativo",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17784576000000000L)
                        });
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.BalcaoCaixaDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("NumeroOperacao")
                        .HasColumnType("text")
                        .HasColumnName("numero_operacao");

                    b.Property<bool>("TemFgi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tem_fgi");

                    b.Property<string>("TipoProduto")
                        .HasColumnType("text")
                        .HasColumnName("tipo_produto");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("balcao_caixa_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BancoId")
                        .HasColumnType("uuid")
                        .HasColumnName("banco_id");

                    b.Property<short>("BaseCalculo")
                        .HasColumnType("smallint")
                        .HasColumnName("base_calculo");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("text")
                        .HasColumnName("codigo_interno");

                    b.Property<Guid?>("ContratoPaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_pai_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<LocalDate>("DataContratacao")
                        .HasColumnType("date")
                        .HasColumnName("data_contratacao");

                    b.Property<LocalDate>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda");

                    b.Property<string>("NumeroExterno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_externo");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaAaDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("taxa_aa");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorPrincipalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_principal");

                    b.HasKey("Id");

                    b.HasIndex("BancoId")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasFilter("codigo_interno IS NOT NULL");

                    b.HasIndex("ContratoPaiId")
                        .HasFilter("contrato_pai_id IS NOT NULL");

                    b.HasIndex("DataVencimento")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Status")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("contrato", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.FgiDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("NumeroOperacaoFgi")
                        .HasColumnType("text")
                        .HasColumnName("numero_operacao_fgi");

                    b.Property<decimal?>("PercentualCobertoBacking")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_coberto");

                    b.Property<decimal?>("TaxaFgiAaDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("taxa_fgi_aa");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("fgi_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.FinimpDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BreakFundingFeePercentual")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("break_funding_fee_percentual");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExportadorNome")
                        .HasColumnType("text")
                        .HasColumnName("exportador_nome");

                    b.Property<string>("ExportadorPais")
                        .HasColumnType("text")
                        .HasColumnName("exportador_pais");

                    b.Property<string>("FaturaReferencia")
                        .HasColumnType("text")
                        .HasColumnName("fatura_referencia");

                    b.Property<string>("Incoterm")
                        .HasColumnType("text")
                        .HasColumnName("incoterm");

                    b.Property<string>("ProdutoImportado")
                        .HasColumnType("text")
                        .HasColumnName("produto_importado");

                    b.Property<LocalDate?>("RofDataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("rof_data_emissao");

                    b.Property<string>("RofNumero")
                        .HasColumnType("text")
                        .HasColumnName("rof_numero");

                    b.Property<bool>("TemMarketFlex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tem_market_flex");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("finimp_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Garantia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<LocalDate>("DataConstituicao")
                        .HasColumnType("date")
                        .HasColumnName("data_constituicao");

                    b.Property<LocalDate?>("DataLiberacaoEfetiva")
                        .HasColumnType("date")
                        .HasColumnName("data_liberacao_efetiva");

                    b.Property<LocalDate?>("DataLiberacaoPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_liberacao_prevista");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("PercentualPrincipalDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_principal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_brl");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ContratoId", "Status");

                    b.ToTable("garantia", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaAlienacaoFiduciariaDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CartorioRegistro")
                        .HasColumnType("text")
                        .HasColumnName("cartorio_registro");

                    b.Property<string>("DescricaoBem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_bem");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<string>("MatriculaOuChassi")
                        .HasColumnType("text")
                        .HasColumnName("matricula_ou_chassi");

                    b.Property<string>("TipoBem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_bem");

                    b.Property<decimal>("ValorAvaliadoDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_avaliado");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_alienacao_fiduciaria_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaAvalDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvalistaDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avalista_documento");

                    b.Property<string>("AvalistaNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avalista_nome");

                    b.Property<string>("AvalistaTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avalista_tipo");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<decimal>("ValorAvalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_aval");

                    b.Property<LocalDate?>("VigenciaAte")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_ate");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_aval_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaBoletoBancarioDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BancoEmissor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("banco_emissor");

                    b.Property<LocalDate>("DataEmissaoInicial")
                        .HasColumnType("date")
                        .HasColumnName("data_emissao_inicial");

                    b.Property<LocalDate>("DataVencimentoFinal")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento_final");

                    b.Property<LocalDate>("DataVencimentoInicial")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento_inicial");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<string>("Periodicidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("periodicidade");

                    b.Property<int>("QuantidadeBoletos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_boletos");

                    b.Property<decimal>("ValorUnitarioDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_boleto_bancario_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaCdbCativoDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BancoCustodia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("banco_custodia");

                    b.Property<LocalDate>("DataEmissaoCdb")
                        .HasColumnType("date")
                        .HasColumnName("data_emissao_cdb");

                    b.Property<LocalDate>("DataVencimentoCdb")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento_cdb");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<string>("NumeroCdb")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_cdb");

                    b.Property<decimal?>("PercentualCdiDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_cdi");

                    b.Property<decimal?>("RendimentoAaDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("rendimento_aa");

                    b.Property<decimal?>("TaxaIrrfAplicacaoDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("taxa_irrf_aplicacao");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_cdb_cativo_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaDuplicatasDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<LocalDate?>("InstrumentoCessaoData")
                        .HasColumnType("date")
                        .HasColumnName("instrumento_cessao_data");

                    b.Property<decimal>("PercentualDescontoDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_desconto");

                    b.Property<int>("QtdDuplicatasCedidas")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_duplicatas_cedidas");

                    b.Property<decimal>("ValorTotalDuplicatasDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_total_duplicatas");

                    b.Property<LocalDate>("VencimentoEscalonadoFim")
                        .HasColumnType("date")
                        .HasColumnName("vencimento_escalonado_fim");

                    b.Property<LocalDate>("VencimentoEscalonadoInicio")
                        .HasColumnType("date")
                        .HasColumnName("vencimento_escalonado_inicio");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_duplicatas_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaFgiDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BancoIntermediario")
                        .HasColumnType("text")
                        .HasColumnName("banco_intermediario");

                    b.Property<string>("CodigoOperacaoBndes")
                        .HasColumnType("text")
                        .HasColumnName("codigo_operacao_bndes");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<decimal>("PercentualCoberturaDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_cobertura");

                    b.Property<decimal?>("TaxaFgiAaDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("taxa_fgi_aa");

                    b.Property<string>("TipoFgi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_fgi");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_fgi_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaRecebiveisCartaoDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<string>("OperadoraCartao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operadora_cartao");

                    b.Property<decimal>("PercentualFaturamentoComprometidoDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_faturamento_comprometido");

                    b.Property<int>("PrazoRecebimentoDias")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_recebimento_dias");

                    b.Property<string>("TermoCessaoUrl")
                        .HasColumnType("text")
                        .HasColumnName("termo_cessao_url");

                    b.Property<string>("TipoRecebivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_recebivel");

                    b.Property<decimal?>("ValorMedioMensalReferenciaDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_medio_mensal_referencia");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_recebiveis_cartao_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaSblcDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BancoEmissor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("banco_emissor");

                    b.Property<decimal?>("ComissaoAaDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("comissao_aa");

                    b.Property<Guid>("GarantiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("garantia_id");

                    b.Property<string>("NumeroSblc")
                        .HasColumnType("text")
                        .HasColumnName("numero_sblc");

                    b.Property<string>("PaisEmissor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pais_emissor");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("text")
                        .HasColumnName("swift_code");

                    b.Property<int>("ValidadeDias")
                        .HasColumnType("integer")
                        .HasColumnName("validade_dias");

                    b.HasKey("Id");

                    b.HasIndex("GarantiaId")
                        .IsUnique();

                    b.ToTable("garantia_sblc_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Lei4131Detail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BreakFundingFeePercentual")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("break_funding_fee_percentual");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("SblcBancoEmissor")
                        .HasColumnType("text")
                        .HasColumnName("sblc_banco_emissor");

                    b.Property<string>("SblcNumero")
                        .HasColumnType("text")
                        .HasColumnName("sblc_numero");

                    b.Property<decimal?>("SblcValorUsd")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("sblc_valor_usd");

                    b.Property<bool>("TemMarketFlex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tem_market_flex");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("lei4131_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.NceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BancoMandatario")
                        .HasColumnType("text")
                        .HasColumnName("banco_mandatario");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<LocalDate?>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_emissao");

                    b.Property<string>("NceNumero")
                        .HasColumnType("text")
                        .HasColumnName("nce_numero");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("nce_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<LocalDate?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<LocalDate>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorJurosDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_juros");

                    b.Property<decimal?>("ValorPagoDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_pago");

                    b.Property<decimal>("ValorPrincipalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_principal");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("ContratoId", "Numero")
                        .IsUnique();

                    b.ToTable("parcela", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.RefinimpDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Guid>("ContratoMaeId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_mae_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("PercentualRefinanciadoDecimal")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percentual_refinanciado");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValorQuitadoNoRefiMoeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("valor_quitado_no_refi_moeda");

                    b.Property<decimal>("ValorQuitadoNoRefiValor")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_quitado_no_refi_valor");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("refinimp_detail", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Cotacoes.CotacaoFx", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fonte");

                    b.Property<string>("MoedaBase")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_base");

                    b.Property<string>("MoedaQuote")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_quote");

                    b.Property<Instant>("Momento")
                        .HasColumnType("timestamptz")
                        .HasColumnName("momento");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorCompraDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_compra");

                    b.Property<decimal>("ValorVendaDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_venda");

                    b.HasKey("Id");

                    b.HasIndex("MoedaBase", "Tipo", "Momento");

                    b.HasIndex("MoedaBase", "MoedaQuote", "Momento", "Tipo")
                        .IsUnique();

                    b.ToTable("cotacao_fx", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Cotacoes.ParametroCotacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<Guid?>("BancoId")
                        .HasColumnType("uuid")
                        .HasColumnName("banco_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Modalidade")
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("TipoCotacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_cotacao");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BancoId", "Modalidade");

                    b.ToTable("parametro_cotacao", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Cronograma.EventoCronograma", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComprovanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("comprovante_url");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<LocalDate?>("DataPagamentoEfetivo")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento_efetivo");

                    b.Property<LocalDate>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda");

                    b.Property<short>("NumeroEvento")
                        .HasColumnType("smallint")
                        .HasColumnName("numero_evento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("SaldoDevedorAposDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("saldo_devedor_apos");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TaxaCambioPagamentoDecimal")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("taxa_cambio_pagamento");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("ValorBrlEstimadoDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_brl_estimado");

                    b.Property<decimal>("ValorMoedaOriginalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_moeda_original");

                    b.Property<decimal?>("ValorPagamentoEfetivoBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_pagamento_efetivo_brl");

                    b.Property<decimal?>("ValorPagamentoEfetivoDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_pagamento_efetivo");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId", "NumeroEvento");

                    b.HasIndex("ContratoId", "DataPrevista", "Tipo");

                    b.ToTable("cronograma_pagamento", "sgcf", t =>
                        {
                            t.HasCheckConstraint("ck_cronograma_valor_nao_negativo", "valor_moeda_original >= 0");
                        });
                });

            modelBuilder.Entity("Sgcf.Domain.Hedge.InstrumentoHedge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContraparteId")
                        .HasColumnType("uuid")
                        .HasColumnName("contraparte_id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<LocalDate>("DataContratacao")
                        .HasColumnType("date")
                        .HasColumnName("data_contratacao");

                    b.Property<LocalDate>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("MoedaBase")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_base");

                    b.Property<string>("MoedaQuote")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("moeda_quote");

                    b.Property<decimal>("NotionalDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("notional");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("StrikeCall")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("strike_call");

                    b.Property<decimal?>("StrikeForward")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("strike_forward");

                    b.Property<decimal?>("StrikePut")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("strike_put");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .IsUnique();

                    b.ToTable("instrumento_hedge", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Hedge.PosicaoSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CalculadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("calculado_em");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Guid>("HedgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("hedge_id");

                    b.Property<decimal>("MtmBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("mtm_brl");

                    b.Property<decimal>("SpotUtilizadoDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("spot_utilizado");

                    b.Property<string>("TipoCotacao")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_cotacao");

                    b.HasKey("Id");

                    b.HasIndex("HedgeId", "CalculadoEm");

                    b.ToTable("posicao_snapshot", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Painel.EbitdaMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("created_by");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<decimal>("ValorBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("valor_brl");

                    b.HasKey("Id");

                    b.HasIndex("Ano", "Mes")
                        .IsUnique()
                        .HasDatabaseName("UX_ebitda_mensal_ano_mes");

                    b.ToTable("ebitda_mensal", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Painel.SnapshotMensalPosicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<Instant>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<decimal>("SaldoPrincipalBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("saldo_principal_brl");

                    b.Property<int>("TotalContratosAtivos")
                        .HasColumnType("integer")
                        .HasColumnName("total_contratos_ativos");

                    b.Property<decimal>("TotalParcelasAbertasBrlDecimal")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("total_parcelas_abertas_brl");

                    b.HasKey("Id");

                    b.HasIndex("Ano", "Mes")
                        .IsUnique()
                        .HasDatabaseName("UX_snapshot_mensal_posicao_ano_mes");

                    b.ToTable("snapshot_mensal_posicao", "sgcf");
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Garantia", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Contrato", null)
                        .WithMany("Garantias")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaAlienacaoFiduciariaDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaAlienacaoFiduciariaDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaAvalDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaAvalDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaBoletoBancarioDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaBoletoBancarioDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaCdbCativoDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaCdbCativoDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaDuplicatasDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaDuplicatasDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaFgiDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaFgiDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaRecebiveisCartaoDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaRecebiveisCartaoDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.GarantiaSblcDetail", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Garantia", null)
                        .WithOne()
                        .HasForeignKey("Sgcf.Domain.Contratos.GarantiaSblcDetail", "GarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Parcela", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Contrato", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Cronograma.EventoCronograma", b =>
                {
                    b.HasOne("Sgcf.Domain.Contratos.Contrato", null)
                        .WithMany("EventosCronograma")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgcf.Domain.Contratos.Contrato", b =>
                {
                    b.Navigation("EventosCronograma");

                    b.Navigation("Garantias");

                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
